name: Deploy to GitHub Pages

# Run on every push to main
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # 1. Checkout code
      - uses: actions/checkout@v3
        # prevent Actions from overwriting our token
        with:
          persist-credentials: false

      # 2. Setup Node.js
      - name: Use Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      # 3. Install deps
      - name: Install dependencies
        run: npm ci

      # 4. Build & deploy
      - name: Build & Publish to gh-pages
        run: npm run deploy
        env:
          # Tells gh-pages CLI to use this token when pushing
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
